CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS formatting_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    font VARCHAR(32) NOT NULL,
    fontsize SMALLINT NOT NULL,
    alignment VARCHAR(32) NOT NULL,
    spacing NUMERIC(3,2) NOT NULL,
    before_spacing NUMERIC(3,2) NOT NULL,
    after_spacing NUMERIC(3,2) NOT NULL,
    first_indentation NUMERIC(3,2) NOT NULL,
    list_tabulation NUMERIC(3,2) NOT NULL,
    have_title VARCHAR(8) NOT NULL
);